# Generated by Django 5.0.6 on 2024-08-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bought', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
